/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import files.ConfigFile;
import java.io.IOException;
import static java.lang.System.exit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import main.LGMIPSV2;

/**
 *
 * @author Asus
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        nFUAdd_JL = new javax.swing.JLabel();
        nFUAdd_JTF = new javax.swing.JTextField();
        latencyAdd_JL = new javax.swing.JLabel();
        latencyAdd_JTF = new javax.swing.JTextField();
        nFUMult_JL = new javax.swing.JLabel();
        nFUMult_JTF = new javax.swing.JTextField();
        latencyFUMult_JL = new javax.swing.JLabel();
        latencyFUMult_JTF = new javax.swing.JTextField();
        sizeROB_JL = new javax.swing.JLabel();
        sizeROB_JTF = new javax.swing.JTextField();
        retirementROB_JL = new javax.swing.JLabel();
        retirementROB_JTF = new javax.swing.JTextField();
        tipusPrediccio_JL = new javax.swing.JLabel();
        ROB_CB = new javax.swing.JCheckBox();
        forwarding_CB = new javax.swing.JCheckBox();
        SchedulerName_JL = new javax.swing.JLabel();
        RandomFile_CB = new javax.swing.JCheckBox();
        SourcePath_JL = new javax.swing.JLabel();
        addressPredictor_CB = new javax.swing.JCheckBox();
        SourcePath_JTF = new javax.swing.JTextField();
        tipusPrediccio_ComboBox = new javax.swing.JComboBox<>();
        CommitCycles_JTF = new javax.swing.JTextField();
        SchedulerName_ComboBox = new javax.swing.JComboBox<>();
        CommitCycles_JL = new javax.swing.JLabel();
        DecodeCycles_JTF = new javax.swing.JTextField();
        DecodeCycles_JL = new javax.swing.JLabel();
        ExecuteCycles_JTF = new javax.swing.JTextField();
        ExecuteCycles_JL = new javax.swing.JLabel();
        SaveClose_BT = new javax.swing.JButton();
        nBitsArchitecture_JL = new javax.swing.JLabel();
        nBitsArchitecture_JTF = new javax.swing.JTextField();
        startAddress_JL = new javax.swing.JLabel();
        startAddress_JTF = new javax.swing.JTextField();
        finishAddress_JL = new javax.swing.JLabel();
        finishAddress_JTF = new javax.swing.JTextField();
        nRegisters_JL = new javax.swing.JLabel();
        nRegisters_JTF = new javax.swing.JTextField();
        fetchCycles_JL = new javax.swing.JLabel();
        fetchCycles_JTF = new javax.swing.JTextField();
        memoryCycles_JL = new javax.swing.JLabel();
        memoryCycles_JTF2 = new javax.swing.JTextField();
        writeCycles_JL = new javax.swing.JLabel();
        writeCycles_JTF3 = new javax.swing.JTextField();
        scalable_JL = new javax.swing.JLabel();
        scalable_JTF = new javax.swing.JTextField();
        nFUGeneric_JL = new javax.swing.JLabel();
        nFUGeneric_JTF = new javax.swing.JTextField();
        latencyGeneric_JL = new javax.swing.JLabel();
        LatencyGeneric_JTF = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton2.setText("Exit");
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setText("Execute");
        jButton1.setToolTipText("");
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/XD.jpeg"))); // NOI18N
        jLabel1.setToolTipText("");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(196, 196, 196)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("MIPS", jPanel1);

        nFUAdd_JL.setText("nFUAdd");

        nFUAdd_JTF.setText(ConfigFile.getnFUAdd()+"");
        nFUAdd_JTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nFUAdd_JTFActionPerformed(evt);
            }
        });

        latencyAdd_JL.setText("latencyAdd");

        latencyAdd_JTF.setText(ConfigFile.getLatencyAdd()+"");
        latencyAdd_JTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                latencyAdd_JTFActionPerformed(evt);
            }
        });

        nFUMult_JL.setText("nFUMult");

        nFUMult_JTF.setText(ConfigFile.getnFUMult()+"");
        nFUMult_JTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nFUMult_JTFActionPerformed(evt);
            }
        });

        latencyFUMult_JL.setText("latencyFUMult");

        latencyFUMult_JTF.setText(ConfigFile.getLatencyMult()+"");
        latencyFUMult_JTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                latencyFUMult_JTFActionPerformed(evt);
            }
        });

        sizeROB_JL.setText("sizeROB");

        sizeROB_JTF.setText(ConfigFile.getSizeROB()+"");
        sizeROB_JTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sizeROB_JTFActionPerformed(evt);
            }
        });

        retirementROB_JL.setText("retirementROB");

        retirementROB_JTF.setText(ConfigFile.getRetirROB()+"");
        retirementROB_JTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retirementROB_JTFActionPerformed(evt);
            }
        });

        tipusPrediccio_JL.setText("tipusPrediccio");

        ROB_CB.setText("ROB");
        ROB_CB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ROB_CBActionPerformed(evt);
            }
        });

        forwarding_CB.setText("forwarding");
        forwarding_CB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forwarding_CBActionPerformed(evt);
            }
        });

        SchedulerName_JL.setText("SchedulerName");

        RandomFile_CB.setText("RandomFile");
        RandomFile_CB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RandomFile_CBActionPerformed(evt);
            }
        });

        SourcePath_JL.setText("SourcePath");

        addressPredictor_CB.setText("addressPredictor");
        addressPredictor_CB.setMaximumSize(new java.awt.Dimension(102, 23));
        addressPredictor_CB.setMinimumSize(new java.awt.Dimension(102, 23));
        addressPredictor_CB.setPreferredSize(new java.awt.Dimension(102, 23));
        addressPredictor_CB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressPredictor_CBActionPerformed(evt);
            }
        });

        SourcePath_JTF.setText(ConfigFile.getSourcePath());
        SourcePath_JTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SourcePath_JTFActionPerformed(evt);
            }
        });

        tipusPrediccio_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Not Taken", "Taken", "One Bit", "Two Bit" }));
        tipusPrediccio_ComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                tipusPrediccio_ComboBoxItemStateChanged(evt);
            }
        });

        CommitCycles_JTF.setText(ConfigFile.getCommitCycles()+"");
        CommitCycles_JTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CommitCycles_JTFActionPerformed(evt);
            }
        });

        SchedulerName_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "enOrden" }));
        SchedulerName_ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SchedulerName_ComboBoxActionPerformed(evt);
            }
        });

        CommitCycles_JL.setText("CommitCycles");

        DecodeCycles_JTF.setText(ConfigFile.getDecodeCycles()+"");
        DecodeCycles_JTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DecodeCycles_JTFActionPerformed(evt);
            }
        });

        DecodeCycles_JL.setText("decodeCycles");

        ExecuteCycles_JTF.setText(ConfigFile.getExecuteCycles()+"");
        ExecuteCycles_JTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExecuteCycles_JTFActionPerformed(evt);
            }
        });

        ExecuteCycles_JL.setText("executeCycles");

        SaveClose_BT.setText("Save & Close");

        nBitsArchitecture_JL.setText("nBits Architecture");

        nBitsArchitecture_JTF.setText(ConfigFile.getnBits()+"");
        nBitsArchitecture_JTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nBitsArchitecture_JTFActionPerformed(evt);
            }
        });

        startAddress_JL.setText("startAddress");

        startAddress_JTF.setText(ConfigFile.getStartAdress()+"");
        startAddress_JTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startAddress_JTFActionPerformed(evt);
            }
        });

        finishAddress_JL.setText("finishAddress");

        finishAddress_JTF.setText(ConfigFile.getFinishAdress()+"");
        finishAddress_JTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishAddress_JTFActionPerformed(evt);
            }
        });

        nRegisters_JL.setText("nRegisters");

        nRegisters_JTF.setText(ConfigFile.getnRegister()+"");
        nRegisters_JTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nRegisters_JTFActionPerformed(evt);
            }
        });

        fetchCycles_JL.setText("fetchCycles");

        fetchCycles_JTF.setText(ConfigFile.getFetchCycles()+"");
        fetchCycles_JTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fetchCycles_JTFActionPerformed(evt);
            }
        });

        memoryCycles_JL.setText("memoryCycles");

        memoryCycles_JTF2.setText(ConfigFile.getMemoryCycles()+"");
        memoryCycles_JTF2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memoryCycles_JTF2ActionPerformed(evt);
            }
        });

        writeCycles_JL.setText("writeCycles");

        writeCycles_JTF3.setText(ConfigFile.getWriteCycles()+"");
        writeCycles_JTF3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                writeCycles_JTF3ActionPerformed(evt);
            }
        });

        scalable_JL.setText("scalable");

        scalable_JTF.setText(ConfigFile.getScalability()+"");
        scalable_JTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scalable_JTFActionPerformed(evt);
            }
        });

        nFUGeneric_JL.setText("nFUGeneric");
        nFUGeneric_JL.setToolTipText("");

        nFUGeneric_JTF.setText(ConfigFile.getnFUGeneric()+"");
        nFUGeneric_JTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nFUGeneric_JTFActionPerformed(evt);
            }
        });

        latencyGeneric_JL.setText("latencyGeneric");

        LatencyGeneric_JTF.setText(ConfigFile.getLatencyGeneric()+"");
        LatencyGeneric_JTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LatencyGeneric_JTFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(writeCycles_JL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(writeCycles_JTF3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(memoryCycles_JL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(memoryCycles_JTF2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(ExecuteCycles_JL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ExecuteCycles_JTF, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(DecodeCycles_JL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DecodeCycles_JTF, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(fetchCycles_JL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fetchCycles_JTF, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(nRegisters_JL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nRegisters_JTF, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(finishAddress_JL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(finishAddress_JTF, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(startAddress_JL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(startAddress_JTF, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(nBitsArchitecture_JL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nBitsArchitecture_JTF, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(SchedulerName_JL)
                                    .addComponent(CommitCycles_JL))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(CommitCycles_JTF)
                                    .addComponent(SchedulerName_ComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(SourcePath_JL)
                                    .addComponent(scalable_JL))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(SourcePath_JTF, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(scalable_JTF)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(latencyAdd_JL)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(latencyAdd_JTF, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(nFUGeneric_JL)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(nFUGeneric_JTF, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(nFUMult_JL)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(nFUMult_JTF, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(latencyGeneric_JL)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(LatencyGeneric_JTF, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(latencyFUMult_JL)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(latencyFUMult_JTF, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(sizeROB_JL)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(sizeROB_JTF, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(retirementROB_JL)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(retirementROB_JTF, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(nFUAdd_JL)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(nFUAdd_JTF, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 2, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(SaveClose_BT)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(tipusPrediccio_JL)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tipusPrediccio_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RandomFile_CB, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addressPredictor_CB, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(forwarding_CB)
                            .addComponent(ROB_CB, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RandomFile_CB)
                    .addComponent(ROB_CB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addressPredictor_CB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(forwarding_CB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nBitsArchitecture_JL, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nBitsArchitecture_JTF))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(startAddress_JL, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(startAddress_JTF))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(finishAddress_JL, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(finishAddress_JTF))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nRegisters_JL, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nRegisters_JTF))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fetchCycles_JL, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fetchCycles_JTF))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DecodeCycles_JL, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DecodeCycles_JTF))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ExecuteCycles_JL, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ExecuteCycles_JTF))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(memoryCycles_JL, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(memoryCycles_JTF2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(writeCycles_JL, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(writeCycles_JTF3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CommitCycles_JL, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CommitCycles_JTF)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(latencyGeneric_JL, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LatencyGeneric_JTF))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nFUAdd_JL, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nFUAdd_JTF))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(latencyAdd_JL, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(latencyAdd_JTF))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nFUMult_JL, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nFUMult_JTF))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(latencyFUMult_JL, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(latencyFUMult_JTF))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sizeROB_JL, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sizeROB_JTF))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(retirementROB_JL, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(retirementROB_JTF))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nFUGeneric_JL, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nFUGeneric_JTF))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(scalable_JL, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(scalable_JTF))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SourcePath_JTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SourcePath_JL, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SchedulerName_JL, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SchedulerName_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tipusPrediccio_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tipusPrediccio_JL, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SaveClose_BT)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Properties", jPanel2);

        files.ConfigRegisters reg = null;
        try {
            reg = new files.ConfigRegisters();
        } catch (Exception e) {
            e.printStackTrace();
        }
        int nregs = reg.getRegistersNumber();
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Register", "Value"
            }
        ));
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        for (int i=0; i<nregs; i++) {
            model.addRow(new Object[]{"r"+i,reg.getRegister(i)});
        }
        jScrollPane1.setViewportView(jTable1);

        jButton3.setText("-");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("+");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Save Config");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 487, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton3)
                    .addComponent(jButton5))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Registers", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 508, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 505, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LatencyGeneric_JTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LatencyGeneric_JTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LatencyGeneric_JTFActionPerformed

    private void nFUGeneric_JTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nFUGeneric_JTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nFUGeneric_JTFActionPerformed

    private void scalable_JTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scalable_JTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_scalable_JTFActionPerformed

    private void writeCycles_JTF3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_writeCycles_JTF3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_writeCycles_JTF3ActionPerformed

    private void memoryCycles_JTF2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memoryCycles_JTF2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_memoryCycles_JTF2ActionPerformed

    private void fetchCycles_JTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fetchCycles_JTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fetchCycles_JTFActionPerformed

    private void nRegisters_JTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nRegisters_JTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nRegisters_JTFActionPerformed

    private void finishAddress_JTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishAddress_JTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_finishAddress_JTFActionPerformed

    private void startAddress_JTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startAddress_JTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_startAddress_JTFActionPerformed

    private void nBitsArchitecture_JTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nBitsArchitecture_JTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nBitsArchitecture_JTFActionPerformed

    private void ExecuteCycles_JTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExecuteCycles_JTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExecuteCycles_JTFActionPerformed

    private void DecodeCycles_JTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DecodeCycles_JTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DecodeCycles_JTFActionPerformed

    private void SchedulerName_ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SchedulerName_ComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SchedulerName_ComboBoxActionPerformed

    private void CommitCycles_JTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CommitCycles_JTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CommitCycles_JTFActionPerformed

    private void tipusPrediccio_ComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_tipusPrediccio_ComboBoxItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_tipusPrediccio_ComboBoxItemStateChanged

    private void SourcePath_JTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SourcePath_JTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SourcePath_JTFActionPerformed

    private void addressPredictor_CBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressPredictor_CBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressPredictor_CBActionPerformed

    private void RandomFile_CBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RandomFile_CBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RandomFile_CBActionPerformed

    private void forwarding_CBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forwarding_CBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_forwarding_CBActionPerformed

    private void ROB_CBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ROB_CBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ROB_CBActionPerformed

    private void retirementROB_JTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retirementROB_JTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_retirementROB_JTFActionPerformed

    private void sizeROB_JTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sizeROB_JTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sizeROB_JTFActionPerformed

    private void latencyFUMult_JTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_latencyFUMult_JTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_latencyFUMult_JTFActionPerformed

    private void nFUMult_JTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nFUMult_JTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nFUMult_JTFActionPerformed

    private void latencyAdd_JTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_latencyAdd_JTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_latencyAdd_JTFActionPerformed

    private void nFUAdd_JTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nFUAdd_JTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nFUAdd_JTFActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        LGMIPSV2 lg = new LGMIPSV2();
        try {
            lg.init();
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) this.jTable1.getModel();
        model.addRow(new Object[]{"Registro N", "Valor"});
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) this.jTable1.getModel();
        int selected = this.jTable1.getSelectedRow();
        if (selected != -1)
        model.removeRow(selected);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("System".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CommitCycles_JL;
    private javax.swing.JTextField CommitCycles_JTF;
    private javax.swing.JLabel DecodeCycles_JL;
    private javax.swing.JTextField DecodeCycles_JTF;
    private javax.swing.JLabel ExecuteCycles_JL;
    private javax.swing.JTextField ExecuteCycles_JTF;
    private javax.swing.JTextField LatencyGeneric_JTF;
    private javax.swing.JCheckBox ROB_CB;
    private javax.swing.JCheckBox RandomFile_CB;
    private javax.swing.JButton SaveClose_BT;
    private javax.swing.JComboBox<String> SchedulerName_ComboBox;
    private javax.swing.JLabel SchedulerName_JL;
    private javax.swing.JLabel SourcePath_JL;
    private javax.swing.JTextField SourcePath_JTF;
    private javax.swing.JCheckBox addressPredictor_CB;
    private javax.swing.JLabel fetchCycles_JL;
    private javax.swing.JTextField fetchCycles_JTF;
    private javax.swing.JLabel finishAddress_JL;
    private javax.swing.JTextField finishAddress_JTF;
    private javax.swing.JCheckBox forwarding_CB;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel latencyAdd_JL;
    private javax.swing.JTextField latencyAdd_JTF;
    private javax.swing.JLabel latencyFUMult_JL;
    private javax.swing.JTextField latencyFUMult_JTF;
    private javax.swing.JLabel latencyGeneric_JL;
    private javax.swing.JLabel memoryCycles_JL;
    private javax.swing.JTextField memoryCycles_JTF2;
    private javax.swing.JLabel nBitsArchitecture_JL;
    private javax.swing.JTextField nBitsArchitecture_JTF;
    private javax.swing.JLabel nFUAdd_JL;
    private javax.swing.JTextField nFUAdd_JTF;
    private javax.swing.JLabel nFUGeneric_JL;
    private javax.swing.JTextField nFUGeneric_JTF;
    private javax.swing.JLabel nFUMult_JL;
    private javax.swing.JTextField nFUMult_JTF;
    private javax.swing.JLabel nRegisters_JL;
    private javax.swing.JTextField nRegisters_JTF;
    private javax.swing.JLabel retirementROB_JL;
    private javax.swing.JTextField retirementROB_JTF;
    private javax.swing.JLabel scalable_JL;
    private javax.swing.JTextField scalable_JTF;
    private javax.swing.JLabel sizeROB_JL;
    private javax.swing.JTextField sizeROB_JTF;
    private javax.swing.JLabel startAddress_JL;
    private javax.swing.JTextField startAddress_JTF;
    private javax.swing.JComboBox<String> tipusPrediccio_ComboBox;
    private javax.swing.JLabel tipusPrediccio_JL;
    private javax.swing.JLabel writeCycles_JL;
    private javax.swing.JTextField writeCycles_JTF3;
    // End of variables declaration//GEN-END:variables
}
